// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Hzfhq5xs_4h04tusA0XZaP4vGLCRZ5k',
    appId: '1:1052289449454:web:c4f75c55b35278a737a2ff',
    messagingSenderId: '1052289449454',
    projectId: 'norumkaraokeweb',
    authDomain: 'norumkaraokeweb.firebaseapp.com',
    storageBucket: 'norumkaraokeweb.appspot.com',
    measurementId: 'G-73XJ7HR92Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCSTfHyY_3siMvKZiPiVCv3lV5x9Et_l4',
    appId: '1:1052289449454:android:308eb7d530038cfa37a2ff',
    messagingSenderId: '1052289449454',
    projectId: 'norumkaraokeweb',
    storageBucket: 'norumkaraokeweb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgwVnHbBN-MvO4G66ckuylHGHmv3NlMu8',
    appId: '1:1052289449454:ios:051ac46bfd3f9a7b37a2ff',
    messagingSenderId: '1052289449454',
    projectId: 'norumkaraokeweb',
    storageBucket: 'norumkaraokeweb.appspot.com',
    iosBundleId: 'com.example.norumkaraoke',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgwVnHbBN-MvO4G66ckuylHGHmv3NlMu8',
    appId: '1:1052289449454:ios:2f93a9ba50ad3f1f37a2ff',
    messagingSenderId: '1052289449454',
    projectId: 'norumkaraokeweb',
    storageBucket: 'norumkaraokeweb.appspot.com',
    iosBundleId: 'com.example.norumkaraoke.RunnerTests',
  );
}
